local all postgres peer map=devel-admin
local all all scram-sha-256
host gitea gitea_app 127.0.0.1/32 scram-sha-256
host all gitea_app 127.0.0.1/32 reject
host all all 127.0.0.1/32 scram-sha-256
host all all 0.0.0.0/0 reject
host all all ::0/0 reject
